Iñigo Martin Melero

## Analisis Random Sample

### 0) Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import GradientBoostingClassifier

np.random.seed(51)

### 1) Preprocesamiento

In [2]:
df1=pd.read_csv('Bancarrota_Total_nd_nooutliers.csv',encoding = 'unicode_escape')
print(df1)

       ID  Coef1_Springate  Coef2_Springate  Coef3_Springate  Coef4_Springate  \
0       2           0.6894           0.1641           0.3116           2.8739   
1       4          -0.0034           0.0296          -0.2114           0.6265   
2       5           0.2916           0.0341           0.0534           0.3098   
3       6           0.3450          -0.1234          -0.1481           0.4249   
4       7           0.0593          -0.3758          -0.7022           0.0811   
..    ...              ...              ...              ...              ...   
837  1493          -0.3422          -0.1538          -0.2613           0.0100   
838  1496           0.0247          -0.1097          -0.0973           0.1505   
839  1497          -0.0206          -0.0668          -0.0340           0.0016   
840  1499           0.0964          -0.2809          -0.3393           0.0100   
841  1502          -0.0555          -0.3837          -0.3051           0.0354   

     Coef1_Amat  Coef2_Amat

In [3]:
df1.dtypes

ID                   int64
Coef1_Springate    float64
Coef2_Springate    float64
Coef3_Springate    float64
Coef4_Springate    float64
Coef1_Amat         float64
Coef2_Amat         float64
Coef3_Amat         float64
Coef4_Amat         float64
Resultado            int64
dtype: object

In [4]:
df2=pd.read_csv('Activa_Total_nd_nooutliers.csv',encoding = 'unicode_escape')
print(df2)

            ID  Coef1_Springate  Coef2_Springate  Coef3_Springate  \
0            1          -0.1786           0.0810           0.2086   
1            2           0.3473           0.0039           0.1439   
2            3           0.4718           0.0385           0.0752   
3            5           0.0656           0.0826           0.5767   
4            7           0.3031           0.0006           0.0030   
...        ...              ...              ...              ...   
388140  732492           0.0111          -0.0076          -0.0069   
388141  732493           0.8986          -0.0367          -0.2176   
388142  732499           0.0051          -0.0130          -0.0203   
388143  732550          -0.0927           0.0000           0.0208   
388144  732570           0.6813          -0.0064          -0.0240   

        Coef4_Springate  Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat  \
0                2.3157      0.9028      0.6267      0.0598      0.0954   
1                1.89

In [5]:
df2.dtypes

ID                   int64
Coef1_Springate    float64
Coef2_Springate    float64
Coef3_Springate    float64
Coef4_Springate    float64
Coef1_Amat         float64
Coef2_Amat         float64
Coef3_Amat         float64
Coef4_Amat         float64
Resultado            int64
dtype: object

In [6]:
df2=df2.sample(n=1445)
df2

ID  Coef1_Springate  Coef2_Springate  Coef3_Springate  \
105814  148365          -0.0018           0.0221           0.0311   
155355  225412           0.3122           0.0291           0.0701   
369763  661895           0.0413           0.2493           0.4053   
198836  297285           0.7045           0.0393           0.0644   
3415      4562           0.0290           0.0378           0.6606   
...        ...              ...              ...              ...   
62854    85934           0.4031           0.1294           0.1568   
41842    56712           0.0098           0.0218           0.6516   
58948    80438           0.3637           0.0281           0.0417   
363225  641600           0.0313           0.0006          -0.0488   
144991  208883           0.1540          -0.0056          -0.0125   

        Coef4_Springate  Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat  \
105814           0.0327      0.4049      0.5499      0.0061      0.0111   
155355           3.8002      1.9019      0.5378      0.0219      0.0406   
369763           1.3624      1.6256      0.3848      0.1870      0.4859   
198836           0.7540      2.4101      0.1096      0.0093      0.0851   
3415             0.1620      5.2700      0.2289      0.0194      0.0847   
...                 ...         ...         ...         ...         ...   
62854            1.8007      1.1118      0.1780      0.0913      0.5132   
41842            0.0410      4.0950      0.8736      0.0338      0.0387   
58948            0.9629      1.1421      0.1814      0.0144      0.0795   
363225           0.1443      0.4071      0.2511     -0.0122     -0.0485   
144991           1.4767      0.6663      0.3898     -0.0031     -0.0081   

        Resultado  
105814          2  
155355          2  
369763          2  
198836          2  
3415            2  
...           ...  
62854           2  
41842           2  
58948           2  
363225          2  
144991          2  

[1445 rows x 10 columns]

### 2) Preparacion datos para ML


In [7]:
df3=pd.concat([df1, df2])
df3=df3.reset_index(drop=True)
df3

ID  Coef1_Springate  Coef2_Springate  Coef3_Springate  \
0          2           0.6894           0.1641           0.3116   
1          4          -0.0034           0.0296          -0.2114   
2          5           0.2916           0.0341           0.0534   
3          6           0.3450          -0.1234          -0.1481   
4          7           0.0593          -0.3758          -0.7022   
...      ...              ...              ...              ...   
2282   85934           0.4031           0.1294           0.1568   
2283   56712           0.0098           0.0218           0.6516   
2284   80438           0.3637           0.0281           0.0417   
2285  641600           0.0313           0.0006          -0.0488   
2286  208883           0.1540          -0.0056          -0.0125   

      Coef4_Springate  Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat  \
0              2.8739      1.7204      0.4234      0.1196      0.2824   
1              0.6265      0.4756      0.2109     -0.1652     -0.7833   
2              0.3098      0.9662      0.3709      0.0299      0.0807   
3              0.4249      0.7613     -0.3175     -0.1566      0.4933   
4              0.0811      0.1077     -0.2699     -0.3977      1.4737   
...               ...         ...         ...         ...         ...   
2282           1.8007      1.1118      0.1780      0.0913      0.5132   
2283           0.0410      4.0950      0.8736      0.0338      0.0387   
2284           0.9629      1.1421      0.1814      0.0144      0.0795   
2285           0.1443      0.4071      0.2511     -0.0122     -0.0485   
2286           1.4767      0.6663      0.3898     -0.0031     -0.0081   

      Resultado  
0             1  
1             1  
2             1  
3             1  
4             1  
...         ...  
2282          2  
2283          2  
2284          2  
2285          2  
2286          2  

[2287 rows x 10 columns]

In [8]:
df3 = df3.sample(frac=1).reset_index(drop=True)
df3

ID  Coef1_Springate  Coef2_Springate  Coef3_Springate  \
0     289831          -0.0601           0.2035           0.3290   
1        987           0.4420           0.0716           0.1667   
2     610443           0.4931          -0.0706          -0.1284   
3        309           0.3804           0.0390           0.0360   
4        602           0.0934          -0.1072          -0.4621   
...      ...              ...              ...              ...   
2282  219860          -0.0969           0.0104           0.0106   
2283     118           0.0405          -0.0032          -0.1287   
2284     620          -0.0167          -0.0391          -0.6801   
2285     291           0.6328           0.0123           0.0122   
2286  272669           0.0042           0.0113           0.0134   

      Coef4_Springate  Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat  \
0              3.9612      1.2499      0.3297      0.1716      0.5204   
1              1.1679      1.7107      0.1274      0.0701      0.5505   
2              1.5547      1.5361      0.3393     -0.0772     -0.2276   
3              0.5369      2.9856      0.3306      0.0017      0.0051   
4              0.4910      1.2813      0.2968     -0.1201     -0.4047   
...               ...         ...         ...         ...         ...   
2282           1.8068      0.9256      0.0176      0.0078      0.4438   
2283           0.5150      0.3729      0.0869     -0.0666     -0.7667   
2284           0.3871      2.4555      0.5937     -0.0393     -0.0661   
2285           0.8588      1.6517      0.1080      0.0052      0.0480   
2286           0.2571      0.3149      0.2069      0.0062      0.0299   

      Resultado  
0             2  
1             1  
2             2  
3             1  
4             1  
...         ...  
2282          2  
2283          1  
2284          1  
2285          1  
2286          2  

[2287 rows x 10 columns]

In [9]:
#GridSearchCV utiliza validación cruzada, y luego nosotros haremos también validación cruzada con nuestros datos, por lo que
#a GridSearchCV no le metemos solamente el Training Set, le metemos TODO. 
X=df3.drop(columns=["Resultado","ID"])
Y=df3.drop(columns=["ID","Coef1_Amat","Coef2_Amat","Coef3_Amat","Coef4_Amat","Coef1_Springate","Coef2_Springate","Coef3_Springate","Coef4_Springate"])

In [10]:
X

Coef1_Springate  Coef2_Springate  Coef3_Springate  Coef4_Springate  \
0             -0.0601           0.2035           0.3290           3.9612   
1              0.4420           0.0716           0.1667           1.1679   
2              0.4931          -0.0706          -0.1284           1.5547   
3              0.3804           0.0390           0.0360           0.5369   
4              0.0934          -0.1072          -0.4621           0.4910   
...               ...              ...              ...              ...   
2282          -0.0969           0.0104           0.0106           1.8068   
2283           0.0405          -0.0032          -0.1287           0.5150   
2284          -0.0167          -0.0391          -0.6801           0.3871   
2285           0.6328           0.0123           0.0122           0.8588   
2286           0.0042           0.0113           0.0134           0.2571   

      Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat  
0         1.2499      0.3297      0.1716      0.5204  
1         1.7107      0.1274      0.0701      0.5505  
2         1.5361      0.3393     -0.0772     -0.2276  
3         2.9856      0.3306      0.0017      0.0051  
4         1.2813      0.2968     -0.1201     -0.4047  
...          ...         ...         ...         ...  
2282      0.9256      0.0176      0.0078      0.4438  
2283      0.3729      0.0869     -0.0666     -0.7667  
2284      2.4555      0.5937     -0.0393     -0.0661  
2285      1.6517      0.1080      0.0052      0.0480  
2286      0.3149      0.2069      0.0062      0.0299  

[2287 rows x 8 columns]

In [11]:
Y

Resultado
0             2
1             1
2             2
3             1
4             1
...         ...
2282          2
2283          1
2284          1
2285          1
2286          2

[2287 rows x 1 columns]

### 3.1) Valores Test de Springate

Calculamos si está comprometida la situación de la empresa según Amat.

Su formula es:

Z = - 0.862 + 1.03 x Coef1 + 3.07 x Coef2 + 0.66 x Coef3 + 0.4 x Coef4

Z positivo empresa bien, Z negativo empresa mal.

Cogemos otro Dataframe, y multiplicamos primero y luego sumamos.

In [12]:
formula_Spr=X
formula_Spr=formula_Spr.drop(columns=["Coef1_Amat","Coef2_Amat","Coef3_Amat","Coef4_Amat"])
formula_Spr.loc[:,'Coef1_Springate'] *= 1.03
formula_Spr.loc[:,'Coef2_Springate'] *= 3.07
formula_Spr.loc[:,'Coef3_Springate'] *= 0.66
formula_Spr.loc[:,'Coef4_Springate'] *= 0.4
formula_Spr["constant"]=-0.862
formula_Spr["Z"] = formula_Spr.sum(axis=1)

formula_Spr["Y_pred_Springate"] = 2
formula_Spr.loc[formula_Spr["Z"] <= 0, "Y_pred_Springate"] = 1
Y_pred_formula_Spr=formula_Spr["Y_pred_Springate"]
print("Accuracy: "+str(accuracy_score(Y, Y_pred_formula_Spr)))
print("F1 score: "+str(f1_score(Y, Y_pred_formula_Spr)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred_formula_Spr)))
print("Confusion matrix:")
confusion_matrix(Y, Y_pred_formula_Spr)

Accuracy: 0.6095321381722781
F1 score: 0.5559423172550969
Kappa: 0.22362910421009052
Confusion matrix:


array([[559, 283],
       [610, 835]], dtype=int64)

### 3.2) Valores Test de Grover

Su formula es:

Z = + 0.057 + 0.02 + 1.650 x Coef1 + 3.404 x Coef2 - 0.016 x Coef3

Z positivo empresa bien, Z negativo empresa mal.

Cogemos otro Dataframe, y multiplicamos primero y luego sumamos.

In [13]:
formula_Gro=X
formula_Gro=formula_Gro.drop(columns=["Coef1_Amat","Coef2_Amat","Coef3_Springate","Coef4_Springate","Coef4_Amat"])
formula_Gro.loc[:,'Coef1_Springate'] *= 1.65
formula_Gro.loc[:,'Coef2_Springate'] *= 3.404
formula_Gro.loc[:,'Coef3_Amat'] *= -0.016
formula_Gro["constant"]=0.077
formula_Gro["Z"] = formula_Gro.sum(axis=1)

formula_Gro["Y_pred_Grover"] = 2
formula_Gro.loc[formula_Gro["Z"] <= 0, "Y_pred_Grover"] = 1
Y_pred_formula_Gro=formula_Gro["Y_pred_Grover"]
print("Accuracy: "+str(accuracy_score(Y, Y_pred_formula_Gro)))
print("F1 score: "+str(f1_score(Y, Y_pred_formula_Gro)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred_formula_Gro)))
print("Confusion matrix:")
confusion_matrix(Y, Y_pred_formula_Gro)

Accuracy: 0.7267162221250547
F1 score: 0.4889615699100572
Kappa: 0.336839106670372
Confusion matrix:


array([[ 299,  543],
       [  82, 1363]], dtype=int64)

### 3.3) Valores Test de Amat

Calculamos si está comprometida la situación de la empresa según Amat. 

Su formula es:

Z = - 3.9 + 1.28 x Coef1 + 6.1 x Coef2 + 6.5 x Coef3 + 4.8 x Coef4

Z positivo empresa bien, Z negativo empresa mal.

Cogemos otro Dataframe, y multiplicamos primero y luego sumamos.

In [14]:
formula_Ama=X
formula_Ama=formula_Ama.drop(columns=["Coef1_Springate","Coef2_Springate","Coef3_Springate","Coef4_Springate"])
formula_Ama.loc[:,'Coef1_Amat'] *= 1.28
formula_Ama.loc[:,'Coef2_Amat'] *= 6.1
formula_Ama.loc[:,'Coef3_Amat'] *= 6.5
formula_Ama.loc[:,'Coef4_Amat'] *= 4.8
formula_Ama["constant"]=-3.9
formula_Ama["Z"] = formula_Ama.sum(axis=1)

formula_Ama["Y_pred_Amat"] = 2
formula_Ama.loc[formula_Ama["Z"] <= 0, "Y_pred_Amat"] = 1
Y_pred_formula_Ama=formula_Ama["Y_pred_Amat"]
print("Accuracy: "+str(accuracy_score(Y, Y_pred_formula_Ama)))
print("F1 score: "+str(f1_score(Y, Y_pred_formula_Ama)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred_formula_Ama)))
print("Confusion matrix:")
confusion_matrix(Y, Y_pred_formula_Ama)

Accuracy: 0.689986882378662
F1 score: 0.6222695791156101
Kappa: 0.36406421155881796
Confusion matrix:


array([[584, 258],
       [451, 994]], dtype=int64)

### 3.4) Combinacion de predicciones

In [15]:
labels_total=pd.concat([Y,Y_pred_formula_Spr, Y_pred_formula_Gro,Y_pred_formula_Ama], axis=1)
print(labels_total.to_string())

      Resultado  Y_pred_Springate  Y_pred_Grover  Y_pred_Amat
0             2                 2              2            2
1             1                 2              2            2
2             2                 1              2            1
3             1                 1              2            2
4             1                 1              1            1
5             1                 1              2            1
6             2                 1              2            1
7             2                 1              2            1
8             1                 2              2            1
9             2                 1              2            1
10            2                 2              2            2
11            1                 1              1            1
12            1                 1              1            1
13            2                 1              2            2
14            2                 2              2            2
15      

In [16]:
bancarrota=labels_total.loc[(labels_total['Resultado']==1)]

In [17]:
at_least_1_bancarrota=sum(bancarrota.sum(axis=1)<7)
print(at_least_1_bancarrota)
all_match_bancarrota=sum(bancarrota.sum(axis=1)==4)
print(all_match_bancarrota)

698
255


### 4) Modelos ML

### 4.1) Estudio con Springate

In [18]:
X_Springate=X.drop(columns=["Coef1_Amat","Coef2_Amat","Coef3_Amat","Coef4_Amat"])
X_Springate

Coef1_Springate  Coef2_Springate  Coef3_Springate  Coef4_Springate
0             -0.0601           0.2035           0.3290           3.9612
1              0.4420           0.0716           0.1667           1.1679
2              0.4931          -0.0706          -0.1284           1.5547
3              0.3804           0.0390           0.0360           0.5369
4              0.0934          -0.1072          -0.4621           0.4910
...               ...              ...              ...              ...
2282          -0.0969           0.0104           0.0106           1.8068
2283           0.0405          -0.0032          -0.1287           0.5150
2284          -0.0167          -0.0391          -0.6801           0.3871
2285           0.6328           0.0123           0.0122           0.8588
2286           0.0042           0.0113           0.0134           0.2571

[2287 rows x 4 columns]

K Nearest Neighbours

In [19]:
grid_params={"n_neighbors":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
             "weights": ["uniform","distance"],
             "metric":["minkowski","euclidean","manhattan"],
             "algorithm":["auto","ball_tree","kd_tree","brute"]}
gs=GridSearchCV(KNeighborsClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate,Y)
gs_res.best_params_

Fitting 10 folds for each of 480 candidates, totalling 4800 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


{'algorithm': 'auto',
 'metric': 'manhattan',
 'n_neighbors': 2,
 'weights': 'uniform'}

In [20]:
knn = KNeighborsClassifier(n_neighbors=2,weights="uniform",metric="manhattan",algorithm="auto")
Y_pred=cross_val_predict(knn, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.6414516834280717
F1 score: 0.5980392156862745
Kappa: 0.2918028676217349


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1

array([[610, 232],
       [588, 857]], dtype=int64)

Random Forest

In [21]:
grid_params={"bootstrap":[True,False],
             "max_features":["auto","sqrt"],
             "max_depth": [10,20,30,40,50],
             "n_estimators":[200,400,600,800,1000]
            }

gs=GridSearchCV(RandomForestClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'bootstrap': False,
 'max_depth': 40,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [22]:
rf = RandomForestClassifier(bootstrap= False, max_depth=40, max_features="sqrt", n_estimators= 200)
Y_pred=cross_val_predict(rf, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\

Accuracy: 0.730214254481854
F1 score: 0.6027044430135221
Kappa: 0.4006597046279987


array([[ 468,  374],
       [ 243, 1202]], dtype=int64)

Decision Tree

In [23]:
grid_params={"criterion":["gini","entropy","log_loss"],
             "splitter":["best","random"],
             "max_depth": [10,20,30,40,50,60,70,80,90,100],
            }

gs=GridSearchCV(tree.DecisionTreeClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate, Y)
gs_res.best_params_

Fitting 10 folds for each of 60 candidates, totalling 600 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_C

{'criterion': 'gini', 'max_depth': 50, 'splitter': 'best'}

In [24]:
clf = tree.DecisionTreeClassifier(criterion= "gini", max_depth=50, splitter="best")
Y_pred=cross_val_predict(clf, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.6987319632706602
F1 score: 0.5896366885050626
Kappa: 0.3516434774200583


array([[ 495,  347],
       [ 342, 1103]], dtype=int64)

Naive Bayes

In [25]:
grid_params={'var_smoothing': np.logspace(0,-9, num=100),
            }

gs=GridSearchCV(GaussianNB(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'var_smoothing': 0.0001}

In [26]:
gnb = GaussianNB(var_smoothing= 0.0001)
Y_pred=cross_val_predict(gnb, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7442063839090511
F1 score: 0.5426114151681002
Kappa: 0.38885602501410355


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 347,  495],
       [  90, 1355]], dtype=int64)

Multi-layer Perceptron Classifier Neural newtork

In [27]:
grid_params={'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
            'activation': ['tanh', 'relu','identity','logistic'],
            'solver': ['sgd', 'adam','lbfgs'],
            'alpha': [0.00001,0.0001,0.001,0.01,0.1],
            'learning_rate': ['constant','adaptive','invscaling'],
            }

gs=GridSearchCV(MLPClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate, Y)
gs_res.best_params_

Fitting 10 folds for each of 540 candidates, totalling 5400 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'activation': 'relu',
 'alpha': 0.01,
 'hidden_layer_sizes': (50, 50, 50),
 'learning_rate': 'invscaling',
 'solver': 'sgd'}

In [28]:
mlp = MLPClassifier(activation="relu",alpha=0.01,hidden_layer_sizes=(50,50,50),learning_rate="invscaling",solver="sgd")
Y_pred=cross_val_predict(mlp, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_p

Accuracy: 0.5618714473108877
F1 score: 0.3650190114068441
Kappa: 0.032871597012317455


array([[288, 554],
       [448, 997]], dtype=int64)

Linear Discriminant Analysis

In [29]:
grid_params={'solver': ['svd', 'lsqr', 'eigen'], 
             } 

gs=GridSearchCV(LinearDiscriminantAnalysis(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Springate, Y)
gs_res.best_params_

Fitting 10 folds for each of 3 candidates, totalling 30 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'solver': 'svd'}

In [30]:
lda = LinearDiscriminantAnalysis(solver="svd")
Y_pred=cross_val_predict(lda, X_Springate, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.739833843463052
F1 score: 0.5110928512736237
Kappa: 0.36760931303818833


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 311,  531],
       [  64, 1381]], dtype=int64)

### 4.2) Estudio con Grover

In [31]:
X_Grover=X.drop(columns=["Coef1_Amat","Coef2_Amat","Coef3_Springate","Coef4_Springate","Coef4_Amat"])
X_Grover

Coef1_Springate  Coef2_Springate  Coef3_Amat
0             -0.0601           0.2035      0.1716
1              0.4420           0.0716      0.0701
2              0.4931          -0.0706     -0.0772
3              0.3804           0.0390      0.0017
4              0.0934          -0.1072     -0.1201
...               ...              ...         ...
2282          -0.0969           0.0104      0.0078
2283           0.0405          -0.0032     -0.0666
2284          -0.0167          -0.0391     -0.0393
2285           0.6328           0.0123      0.0052
2286           0.0042           0.0113      0.0062

[2287 rows x 3 columns]

K Nearest Neighbours

In [32]:
grid_params={"n_neighbors":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
             "weights": ["uniform","distance"],
             "metric":["minkowski","euclidean","manhattan"],
             "algorithm":["auto","ball_tree","kd_tree","brute"]}
gs=GridSearchCV(KNeighborsClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover,Y)
gs_res.best_params_

Fitting 10 folds for each of 480 candidates, totalling 4800 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


{'algorithm': 'auto',
 'metric': 'minkowski',
 'n_neighbors': 2,
 'weights': 'uniform'}

In [33]:
knn = KNeighborsClassifier(n_neighbors=2,weights="uniform",metric="minkowski",algorithm="auto")
Y_pred=cross_val_predict(knn, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.6335811106252733
F1 score: 0.5814185814185815
Kappa: 0.2699397440283049


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1

array([[582, 260],
       [578, 867]], dtype=int64)

Random Forest

In [34]:
grid_params={"bootstrap":[True,False],
             "max_features":["auto","sqrt"],
             "max_depth": [10,20,30,40,50],
             "n_estimators":[200,400,600,800,1000]
            }

gs=GridSearchCV(RandomForestClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'bootstrap': False,
 'max_depth': 50,
 'max_features': 'sqrt',
 'n_estimators': 400}

In [35]:
rf = RandomForestClassifier(bootstrap= False, max_depth=50, max_features="sqrt", n_estimators= 400)
Y_pred=cross_val_predict(rf, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\

Accuracy: 0.7315260166156536
F1 score: 0.6023316062176165
Kappa: 0.402195865404264


array([[ 465,  377],
       [ 237, 1208]], dtype=int64)

Decision Tree

In [36]:
grid_params={"criterion":["gini","entropy","log_loss"],
             "splitter":["best","random"],
             "max_depth": [10,20,30,40,50,60,70,80,90,100],
            }

gs=GridSearchCV(tree.DecisionTreeClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover, Y)
gs_res.best_params_

Fitting 10 folds for each of 60 candidates, totalling 600 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_C

{'criterion': 'gini', 'max_depth': 100, 'splitter': 'random'}

In [37]:
clf = tree.DecisionTreeClassifier(criterion= "gini", max_depth=100, splitter="random")
Y_pred=cross_val_predict(clf, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.6816790555312636
F1 score: 0.5682087781731909
Kappa: 0.3161317776410445


array([[ 479,  363],
       [ 365, 1080]], dtype=int64)

Naive Bayes

In [38]:
grid_params={'var_smoothing': np.logspace(0,-9, num=100),
            }

gs=GridSearchCV(GaussianNB(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'var_smoothing': 0.0008111308307896872}

In [39]:
gnb = GaussianNB(var_smoothing= 0.0008)
Y_pred=cross_val_predict(gnb, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7363358111062527
F1 score: 0.5350809560524287
Kappa: 0.3731595045315518


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 347,  495],
       [ 108, 1337]], dtype=int64)

Multi-layer Perceptron Classifier Neural newtork

In [40]:
grid_params={'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
            'activation': ['tanh', 'relu','identity','logistic'],
            'solver': ['sgd', 'adam','lbfgs'],
            'alpha': [0.00001,0.0001,0.001,0.01,0.1],
            'learning_rate': ['constant','adaptive','invscaling'],
            }

gs=GridSearchCV(MLPClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover, Y)
gs_res.best_params_

Fitting 10 folds for each of 540 candidates, totalling 5400 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'activation': 'tanh',
 'alpha': 0.001,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'invscaling',
 'solver': 'sgd'}

In [41]:
mlp = MLPClassifier(activation="tanh",alpha=0.001,hidden_layer_sizes=(100,),learning_rate="invscaling",solver="sgd")
Y_pred=cross_val_predict(mlp, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_p

Accuracy: 0.5203323130738959
F1 score: 0.35659824046920824
Kappa: -0.025672484089609204


array([[304, 538],
       [559, 886]], dtype=int64)

Linear Discriminant Analysis

In [42]:
grid_params={'solver': ['svd', 'lsqr', 'eigen'], 
             } 

gs=GridSearchCV(LinearDiscriminantAnalysis(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Grover, Y)
gs_res.best_params_

Fitting 10 folds for each of 3 candidates, totalling 30 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'solver': 'svd'}

In [43]:
lda = LinearDiscriminantAnalysis(solver="svd")
Y_pred=cross_val_predict(lda, X_Grover, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7472671622212506
F1 score: 0.4866785079928952
Kappa: 0.3696016893461128


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 274,  568],
       [  10, 1435]], dtype=int64)

### 4.3) Estudio con Amat

In [44]:
X_Amat=X.drop(columns=["Coef1_Springate","Coef2_Springate","Coef3_Springate","Coef4_Springate"])
X_Amat

Coef1_Amat  Coef2_Amat  Coef3_Amat  Coef4_Amat
0         1.2499      0.3297      0.1716      0.5204
1         1.7107      0.1274      0.0701      0.5505
2         1.5361      0.3393     -0.0772     -0.2276
3         2.9856      0.3306      0.0017      0.0051
4         1.2813      0.2968     -0.1201     -0.4047
...          ...         ...         ...         ...
2282      0.9256      0.0176      0.0078      0.4438
2283      0.3729      0.0869     -0.0666     -0.7667
2284      2.4555      0.5937     -0.0393     -0.0661
2285      1.6517      0.1080      0.0052      0.0480
2286      0.3149      0.2069      0.0062      0.0299

[2287 rows x 4 columns]

K Nearest Neighbours

In [45]:
grid_params={"n_neighbors":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
             "weights": ["uniform","distance"],
             "metric":["minkowski","euclidean","manhattan"],
             "algorithm":["auto","ball_tree","kd_tree","brute"]}
gs=GridSearchCV(KNeighborsClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat,Y)
gs_res.best_params_

Fitting 10 folds for each of 480 candidates, totalling 4800 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


{'algorithm': 'auto',
 'metric': 'minkowski',
 'n_neighbors': 2,
 'weights': 'uniform'}

In [46]:
knn = KNeighborsClassifier(n_neighbors=2,weights="uniform",metric="minkowski",algorithm="auto")
Y_pred=cross_val_predict(knn, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7026672496720595
F1 score: 0.6565656565656565
Kappa: 0.4045794044722014


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1

array([[650, 192],
       [488, 957]], dtype=int64)

Random Forest

In [47]:
grid_params={"bootstrap":[True,False],
             "max_features":["auto","sqrt"],
             "max_depth": [10,20,30,40,50],
             "n_estimators":[200,400,600,800,1000]
            }

gs=GridSearchCV(RandomForestClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'bootstrap': False,
 'max_depth': 40,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [48]:
rf = RandomForestClassifier(bootstrap= False, max_depth=40, max_features="sqrt", n_estimators= 200)
Y_pred=cross_val_predict(rf, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\

Accuracy: 0.7726278968080454
F1 score: 0.6717171717171717
Kappa: 0.49886223810406727


array([[ 532,  310],
       [ 210, 1235]], dtype=int64)

Decision Tree

In [49]:
grid_params={"criterion":["gini","entropy","log_loss"],
             "splitter":["best","random"],
             "max_depth": [10,20,30,40,50,60,70,80,90,100],
            }

gs=GridSearchCV(tree.DecisionTreeClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat, Y)
gs_res.best_params_

Fitting 10 folds for each of 60 candidates, totalling 600 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_C

{'criterion': 'entropy', 'max_depth': 40, 'splitter': 'best'}

In [50]:
clf = tree.DecisionTreeClassifier(criterion= "entropy", max_depth=40, splitter="best")
Y_pred=cross_val_predict(clf, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7477044162658505
F1 score: 0.66158357771261
Kappa: 0.46051684291731576


array([[ 564,  278],
       [ 299, 1146]], dtype=int64)

Naive Bayes

In [51]:
grid_params={'var_smoothing': np.logspace(0,-9, num=100),
            }

gs=GridSearchCV(GaussianNB(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'var_smoothing': 1.5199110829529332e-05}

In [52]:
gnb = GaussianNB(var_smoothing= 0.0000152)
Y_pred=cross_val_predict(gnb, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7695671184958461
F1 score: 0.6363008971704625
Kappa: 0.4740750760906324


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 461,  381],
       [ 146, 1299]], dtype=int64)

Multi-layer Perceptron Classifier Neural newtork

In [53]:
grid_params={'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
            'activation': ['tanh', 'relu','identity','logistic'],
            'solver': ['sgd', 'adam','lbfgs'],
            'alpha': [0.00001,0.0001,0.001,0.01,0.1],
            'learning_rate': ['constant','adaptive','invscaling'],
            }

gs=GridSearchCV(MLPClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat, Y)
gs_res.best_params_

Fitting 10 folds for each of 540 candidates, totalling 5400 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


{'activation': 'tanh',
 'alpha': 0.001,
 'hidden_layer_sizes': (50, 100, 50),
 'learning_rate': 'invscaling',
 'solver': 'lbfgs'}

In [54]:
mlp = MLPClassifier(activation="tanh",alpha=0.001,hidden_layer_sizes=(50,100,50),learning_rate="invscaling",solver="lbfgs")
Y_pred=cross_val_predict(mlp, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  

Accuracy: 0.790118058592042
F1 score: 0.6743554952510177
Kappa: 0.524109678118565


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


array([[ 497,  345],
       [ 135, 1310]], dtype=int64)

Linear Discriminant Analysis

In [55]:
grid_params={'solver': ['svd', 'lsqr', 'eigen'], 
             } 

gs=GridSearchCV(LinearDiscriminantAnalysis(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X_Amat, Y)
gs_res.best_params_

Fitting 10 folds for each of 3 candidates, totalling 30 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'solver': 'svd'}

In [56]:
lda = LinearDiscriminantAnalysis(solver="svd")
Y_pred=cross_val_predict(lda, X_Amat, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7538259728902492
F1 score: 0.5618677042801556
Kappa: 0.41280965786400214


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 361,  481],
       [  82, 1363]], dtype=int64)

### 4.4) Estudio con todo

K Nearest Neighbours

In [57]:
grid_params={"n_neighbors":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
             "weights": ["uniform","distance"],
             "metric":["minkowski","euclidean","manhattan"],
             "algorithm":["auto","ball_tree","kd_tree","brute"]}
gs=GridSearchCV(KNeighborsClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X,Y)
gs_res.best_params_

Fitting 10 folds for each of 480 candidates, totalling 4800 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


{'algorithm': 'auto',
 'metric': 'minkowski',
 'n_neighbors': 2,
 'weights': 'uniform'}

In [58]:
knn = KNeighborsClassifier(n_neighbors=2,weights="uniform",metric="minkowski",algorithm="auto")
Y_pred=cross_val_predict(knn, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7035417577612593
F1 score: 0.6494312306101344
Kappa: 0.39995820643698266


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1

array([[628, 214],
       [464, 981]], dtype=int64)

Random Forest

In [59]:
grid_params={"bootstrap":[True,False],
             "max_features":["auto","sqrt"],
             "max_depth": [10,20,30,40,50],
             "n_estimators":[200,400,600,800,1000]
            }

gs=GridSearchCV(RandomForestClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'bootstrap': False,
 'max_depth': 30,
 'max_features': 'sqrt',
 'n_estimators': 200}

In [60]:
rf = RandomForestClassifier(bootstrap= False, max_depth=30, max_features="sqrt", n_estimators= 200)
Y_pred=cross_val_predict(rf, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\

Accuracy: 0.7905553126366419
F1 score: 0.6834104428288169
Kappa: 0.5298937847036413


array([[ 517,  325],
       [ 154, 1291]], dtype=int64)

Decision Tree

In [61]:
grid_params={"criterion":["gini","entropy","log_loss"],
             "splitter":["best","random"],
             "max_depth": [10,20,30,40,50,60,70,80,90,100],
            }

gs=GridSearchCV(tree.DecisionTreeClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X, Y)
gs_res.best_params_

Fitting 10 folds for each of 60 candidates, totalling 600 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
200 fits failed out of a total of 600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
200 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_C

{'criterion': 'gini', 'max_depth': 100, 'splitter': 'random'}

In [62]:
clf = tree.DecisionTreeClassifier(criterion= "gini", max_depth=100, splitter="random")
Y_pred=cross_val_predict(clf, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7341495408832531
F1 score: 0.6427732079905993
Kappa: 0.43111175116621403


array([[ 547,  295],
       [ 313, 1132]], dtype=int64)

Naive Bayes

In [63]:
grid_params={'var_smoothing': np.logspace(0,-9, num=100),
            }

gs=GridSearchCV(GaussianNB(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X, Y)
gs_res.best_params_

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'var_smoothing': 1e-05}

In [64]:
gnb = GaussianNB(var_smoothing= 0.00001)
Y_pred=cross_val_predict(gnb, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7765631832094447
F1 score: 0.6383581033262562
Kappa: 0.4851656433771945


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 451,  391],
       [ 120, 1325]], dtype=int64)

Multi-layer Perceptron Classifier Neural newtork

In [65]:
grid_params={'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
            'activation': ['tanh', 'relu','identity','logistic'],
            'solver': ['sgd', 'adam','lbfgs'],
            'alpha': [0.00001,0.0001,0.001,0.01,0.1],
            'learning_rate': ['constant','adaptive','invscaling'],
            }

gs=GridSearchCV(MLPClassifier(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X, Y)
gs_res.best_params_

Fitting 10 folds for each of 540 candidates, totalling 5400 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


{'activation': 'relu',
 'alpha': 0.0001,
 'hidden_layer_sizes': (50, 100, 50),
 'learning_rate': 'invscaling',
 'solver': 'adam'}

In [66]:
mlp = MLPClassifier(activation="relu",alpha=0.0001,hidden_layer_sizes=(50,100,50),learning_rate="invscaling",solver="adam")
Y_pred=cross_val_predict(mlp, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1109: DataConversionWarning: A column

Accuracy: 0.7818102317446436
F1 score: 0.6778566817301485
Kappa: 0.5147852336865826


array([[ 525,  317],
       [ 182, 1263]], dtype=int64)

Linear Discriminant Analysis

In [67]:
grid_params={'solver': ['svd', 'lsqr', 'eigen'], 
             } 

gs=GridSearchCV(LinearDiscriminantAnalysis(),grid_params,verbose=1,cv=10,n_jobs=-1,scoring="recall")
gs_res=gs.fit(X, Y)
gs_res.best_params_

Fitting 10 folds for each of 3 candidates, totalling 30 fits


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'solver': 'svd'}

In [68]:
lda = LinearDiscriminantAnalysis(solver="svd")
Y_pred=cross_val_predict(lda, X, Y, cv=10)
print("Accuracy: "+str(accuracy_score(Y, Y_pred)))
print("F1 score: "+str(f1_score(Y, Y_pred)))
print("Kappa: "+str(cohen_kappa_score(Y, Y_pred)))
conf_mat = confusion_matrix(Y, Y_pred)
conf_mat

Accuracy: 0.7573240052470486
F1 score: 0.5785876993166288
Kappa: 0.4262026808264985


C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\inima\anaconda3\envs\lamda_ssl\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array w

array([[ 381,  461],
       [  94, 1351]], dtype=int64)